export const inboxFixtures = [
  {
    id: 'mail-01',
    sender: 'AutoMotion Parts',
    senderEmail: 'billing@automotion.example',
    senderShort: 'AutoMotion',
    initials: 'AP',
    subject: 'Fwd: Invoice AM-2026-1042 - brake pads',
    preview: 'Resending the January brake-parts invoice for your records.',
    time: '09:42',
    attachments: 1,
    tag: 'Duplicate signal',
    tone: 'danger',
    unread: true,
    sampleFiles: ['auto-1042-resubmitted.pdf', 'auto-1042-original.pdf'],
    pairId: 'inv-1042-a-inv-1042-b',
  },
  {
    id: 'mail-02',
    sender: 'AutoMotion Parts',
    senderEmail: 'billing@automotion.example',
    senderShort: 'AutoMotion',
    initials: 'AP',
    subject: 'Invoice AM-2026-1042 attached',
    preview: 'Please find attached our January brake-parts invoice. Net 30 terms.',
    time: '09:18',
    attachments: 1,
    tag: 'Reference found',
    tone: 'warning',
    unread: false,
    sampleFiles: ['auto-1042-original.pdf', 'auto-1042-resubmitted.pdf'],
    pairId: 'inv-1042-a-inv-1042-b',
  },
  {
    id: 'mail-03',
    sender: 'AutoMotion Parts',
    senderEmail: 'billing@automotion.example',
    senderShort: 'AutoMotion',
    initials: 'AP',
    subject: 'Invoice AM-2026-1043 - February parts',
    preview: 'February replenishment invoice attached for PO-8841.',
    time: '08:51',
    attachments: 1,
    tag: 'Recurring pattern',
    tone: 'success',
    unread: false,
    sampleFiles: ['auto-1043-recurring.pdf', 'auto-1042-original.pdf'],
    pairId: 'inv-1042-a-inv-1043',
  },
  {
    id: 'mail-04',
    sender: 'TorqueLine Components',
    senderEmail: 'ap@torqueline.example',
    senderShort: 'TorqueLine',
    initials: 'TC',
    subject: 'Corrected invoice TL-8812',
    preview: 'Please ignore TL-8811. The corrected invoice for rotors is attached.',
    time: 'Yesterday',
    attachments: 2,
    sampleFiles: ['torque-8812-corrected.pdf', 'torque-8811-original.pdf'],
    tag: 'Needs review',
    tone: 'warning',
    unread: true,
  },
  {
    id: 'mail-05',
    sender: 'Ruta Norte Logistics',
    senderEmail: 'billing@rutanorte.example',
    senderShort: 'Ruta Norte',
    initials: 'RN',
    subject: 'March freight invoice RN-3901',
    preview: 'Freight for the Monterrey distribution lane is attached.',
    time: 'Yesterday',
    attachments: 1,
    sampleFiles: ['ruta-3901-missing-po.pdf'],
    tag: 'Missing PO',
    tone: 'warning',
    unread: false,
  },
  {
    id: 'mail-06',
    sender: 'GaragePro Wholesale',
    senderEmail: 'billing@garagepro.example',
    senderShort: 'GaragePro',
    initials: 'GW',
    subject: 'Credit memo CM-204 applied to GP-7710',
    preview: 'Credit memo attached for the returned alternator units.',
    time: 'Mon',
    attachments: 2,
    sampleFiles: ['garage-204-credit-memo.pdf', 'garage-7710-invoice.pdf'],
    tag: 'Credit memo',
    tone: 'neutral',
    unread: false,
  },
  {
    id: 'mail-07',
    sender: 'FleetFix Supply',
    senderEmail: 'invoices@fleetfix.example',
    senderShort: 'FleetFix',
    initials: 'FS',
    subject: 'Invoice FF-2026-031 - wiper blades',
    preview: 'Final invoice attached for the March fleet replenishment.',
    time: 'Fri',
    attachments: 1,
    sampleFiles: ['fleetfix-031-clear.pdf'],
    tag: 'Clear',
    tone: 'success',
    unread: false,
  },
  {
    id: 'mail-08',
    sender: 'AxleWorks Components',
    senderEmail: 'billing@axleworks.example',
    senderShort: 'AxleWorks',
    initials: 'AC',
    subject: 'Invoice AW-5520 - revised quantity',
    preview: 'Updated total reflects the approved quantity change for hubs.',
    time: 'Fri',
    attachments: 2,
    sampleFiles: ['axle-5520-revised.pdf', 'axle-5520-original.pdf'],
    tag: 'Amount changed',
    tone: 'warning',
    unread: false,
  },
  {
    id: 'mail-09',
    sender: 'Boreal Fleet Maintenance',
    senderEmail: 'billing@borealfleet.example',
    senderShort: 'Boreal Fleet',
    initials: 'BF',
    subject: 'Monthly maintenance invoice - April',
    preview: 'Routine fleet inspection and maintenance services for April.',
    time: 'Thu',
    attachments: 1,
    sampleFiles: ['boreal-032-april.pdf', 'boreal-031-march.pdf'],
    tag: 'Recurring pattern',
    tone: 'success',
    unread: false,
    pairId: 'inv-boreal-mar-inv-boreal-apr',
  },
  {
    id: 'mail-10',
    sender: 'Scanline Auto Supply',
    senderEmail: 'billing@scanline.example',
    senderShort: 'Scanline',
    initials: 'SA',
    subject: 'Invoice attached - scan may be incomplete',
    preview: 'The second page contains the tax and total lines.',
    time: 'Wed',
    attachments: 1,
    sampleFiles: ['scanline-9008-low-confidence-scanned.pdf'],
    tag: 'OCR confidence',
    tone: 'warning',
    unread: true,
  }
];

export function inboxSummary(threads) {
  const attention = threads.filter((thread) => thread.tone === 'danger' || thread.tone === 'warning').length;
  return { total: threads.length, attention };
}
