export const inboxFixtures = [
  {
    id: 'mail-01',
    sender: 'Northstar Office Supply',
    senderShort: 'Northstar',
    initials: 'NO',
    subject: 'Fwd: Invoice NS-1042 - January supplies',
    preview: 'Resending the January invoice for your records.',
    time: '09:42',
    attachments: 1,
    tag: 'Duplicate signal',
    tone: 'danger',
    unread: true,
    pairId: 'inv-1042-a-inv-1042-b',
    agentMessage: 'I found a second copy of NS-1042 in the reference set. The email says “resending”, and the invoice number, PO, total, and service period all agree.'
  },
  {
    id: 'mail-02',
    sender: 'Northstar Office Supply',
    senderShort: 'Northstar',
    initials: 'NO',
    subject: 'Invoice NS-1042 attached',
    preview: 'Please find attached our January invoice. Net 30 terms.',
    time: '09:18',
    attachments: 1,
    tag: 'Reference found',
    tone: 'warning',
    unread: false,
    pairId: 'inv-1042-a-inv-1042-b',
    agentMessage: 'This looks like the earlier copy of the same invoice. I am keeping both messages in the same review thread.'
  },
  {
    id: 'mail-03',
    sender: 'Northstar Office Supply',
    senderShort: 'Northstar',
    initials: 'NO',
    subject: 'Invoice NS-1043 - February supplies',
    preview: 'February replenishment invoice attached for PO-8841.',
    time: '08:51',
    attachments: 1,
    tag: 'Recurring pattern',
    tone: 'success',
    unread: false,
    pairId: 'inv-1042-a-inv-1043',
    agentMessage: 'This invoice resembles January on vendor, PO, and amount, but its service period is February. I am treating it as a likely recurring charge.'
  },
  {
    id: 'mail-04',
    sender: 'Acme Industrial Parts',
    senderShort: 'Acme Parts',
    initials: 'AI',
    subject: 'Corrected invoice INV-8812',
    preview: 'Please ignore INV-8811. The corrected invoice is attached.',
    time: 'Yesterday',
    attachments: 2,
    tag: 'Needs review',
    tone: 'warning',
    unread: true,
    agentMessage: 'The sender explicitly references a corrected invoice. I would compare the two attachments before clearing either one.'
  },
  {
    id: 'mail-05',
    sender: 'Brightline Logistics',
    senderShort: 'Brightline',
    initials: 'BL',
    subject: 'March freight invoice',
    preview: 'Invoice BL-3901 for lane MX-CUN attached.',
    time: 'Yesterday',
    attachments: 1,
    tag: 'Missing PO',
    tone: 'warning',
    unread: false,
    agentMessage: 'I extracted an invoice total, but could not find a purchase order reference. This case needs supporting context before a duplicate decision.'
  },
  {
    id: 'mail-06',
    sender: 'Medico Office Services',
    senderShort: 'Medico',
    initials: 'MO',
    subject: 'Credit memo CM-204 applied to INV-7710',
    preview: 'Credit memo attached for the returned equipment.',
    time: 'Mon',
    attachments: 2,
    tag: 'Credit memo',
    tone: 'neutral',
    unread: false,
    agentMessage: 'This thread contains a credit memo, not a second invoice. I would keep it visible but avoid classifying it as a duplicate payment.'
  },
  {
    id: 'mail-07',
    sender: 'Cedar & Co. Catering',
    senderShort: 'Cedar & Co.',
    initials: 'CC',
    subject: 'Invoice 2026-031 - event services',
    preview: 'Final invoice attached. Service date is March 14.',
    time: 'Fri',
    attachments: 1,
    tag: 'Clear',
    tone: 'success',
    unread: false,
    agentMessage: 'I found no strong duplicate candidate in the current sample set. The invoice can continue through the normal workflow.'
  },
  {
    id: 'mail-08',
    sender: 'Atlas Components',
    senderShort: 'Atlas',
    initials: 'AC',
    subject: 'Invoice AC-5520 - revised amount',
    preview: 'Updated total reflects the approved quantity change.',
    time: 'Fri',
    attachments: 2,
    tag: 'Amount changed',
    tone: 'warning',
    unread: false,
    agentMessage: 'The supplier describes an approved quantity change. The original and revised totals should be reconciled before one is released.'
  },
  {
    id: 'mail-09',
    sender: 'Evergreen Facilities',
    senderShort: 'Evergreen',
    initials: 'EF',
    subject: 'Monthly maintenance invoice - April',
    preview: 'Routine maintenance services for April.',
    time: 'Thu',
    attachments: 1,
    tag: 'Recurring pattern',
    tone: 'success',
    unread: false,
    agentMessage: 'The subject and service period suggest a recurring monthly charge. I would compare it to March rather than flag it as an accidental duplicate.'
  },
  {
    id: 'mail-10',
    sender: 'Papertrail Print Co.',
    senderShort: 'Papertrail',
    initials: 'PP',
    subject: 'Invoice attached - scan may be incomplete',
    preview: 'The second page contains the tax and total lines.',
    time: 'Wed',
    attachments: 1,
    tag: 'OCR confidence',
    tone: 'warning',
    unread: true,
    agentMessage: 'The scan is low quality and the total is on a separate page. I can continue with OCR, but the extracted fields need human verification.'
  }
];

export function inboxSummary(threads) {
  const attention = threads.filter((thread) => thread.tone === 'danger' || thread.tone === 'warning').length;
  return { total: threads.length, attention };
}
